In [1]:
#1.
age = 30
if age >= 25:
    print("Renting a car is more affordable")
elif age <=25:
    print("Renting a car is very expensive")

Renting a car is more affordable


In [39]:
#2.
age = 8
if age >= 25:
    print("Renting a car is more affordable.")
elif 25 > age >= 18:
    print("Renting a car is very expensive.")
else: 
    print("You cannot legally rent a car.")
    

You cannot legally rent a car.


In [66]:
#3. 
dog_phrase = "The quick brown fox jumps over the lazy dog"
vowel_list = []
for words in dog_phrase:
    if words == 'a':
        vowel_list.append(words)
    elif words == 'e':
        vowel_list.append(words)
    elif words == 'i':
        vowel_list.append(words)
    elif words == 'o':
        vowel_list.append(words)
    elif words == 'u':
        vowel_list.append(words)
print(len(dog_phrase))
print(vowel_list)




43
['e', 'u', 'i', 'o', 'o', 'u', 'o', 'e', 'e', 'a', 'o']


In [40]:
#4.
couture = ["trousers", "blouse", "bandana", "cumber band", "blazer", "vest", "french beret", "scarf", "stole"]
panettone = {"cerise", "fuchsia", "aqua", "maple", "auburn", "burnt sienna", "gunmetal blue", "Dark Sapphire"}
for type in couture:
    for color in panettone:
        print(type, color)



trousers auburn
trousers maple
trousers cerise
trousers aqua
trousers fuchsia
trousers Dark Sapphire
trousers burnt sienna
trousers gunmetal blue
blouse auburn
blouse maple
blouse cerise
blouse aqua
blouse fuchsia
blouse Dark Sapphire
blouse burnt sienna
blouse gunmetal blue
bandana auburn
bandana maple
bandana cerise
bandana aqua
bandana fuchsia
bandana Dark Sapphire
bandana burnt sienna
bandana gunmetal blue
cumber band auburn
cumber band maple
cumber band cerise
cumber band aqua
cumber band fuchsia
cumber band Dark Sapphire
cumber band burnt sienna
cumber band gunmetal blue
blazer auburn
blazer maple
blazer cerise
blazer aqua
blazer fuchsia
blazer Dark Sapphire
blazer burnt sienna
blazer gunmetal blue
vest auburn
vest maple
vest cerise
vest aqua
vest fuchsia
vest Dark Sapphire
vest burnt sienna
vest gunmetal blue
french beret auburn
french beret maple
french beret cerise
french beret aqua
french beret fuchsia
french beret Dark Sapphire
french beret burnt sienna
french beret gunmetal

In [64]:
#5.
total = 0 
for i in range(100):
    total += i 
print(total)
    


4950


In [87]:
#6.
fruits = ["apple", "banana", "cherry"]
print(fruits[1])
#7. 
fruits[0] = 'kiwi'
#8. 
fruits.append("orange")
#9. 
fruits.insert(1, "lemon")
#10. 
fruits.remove("banana")
#11. 
fruits2 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(fruits2[-3:-1])
#12. 
print(fruits2[2:5])
#13. 
print(len(fruits2))
#14. 
fruits3 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
fruits3.sort(reverse = True)
print(fruits3)


banana
['kiwi', 'melon']
['cherry', 'orange', 'kiwi']
7
['orange', 'melon', 'mango', 'kiwi', 'cherry', 'banana', 'apple']
2022-11-18 22:34:20.901662
Hi Jimmy, Hope you have a happy Monday
Hi Jimmy, Hope you have a happy Sunday


In [ ]:

#15. 
import datetime as dt 
today = dt.datetime.now()
print(today)


In [ ]:

#16. 

def name_and_day(name, day = "Sunday"):
    print("Hi " + name +", " +"Hope you have a happy " + day)
name_and_day("Jimmy", "Monday")
name_and_day("Jimmy")
    
    


In [98]:
#17. 
import numpy as np
my_np = np.arange(12).reshape((2, 3, 2))
print(my_np)

#18. 
import numpy as np
my_np2 = np.linspace(start = 0, stop = 20, num=6)
print(my_np2)
# 19. 
my_np2_copy = my_np2.copy()


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0.  4.  8. 12. 16. 20.]


##### 20. Array are more compact than lists, use less space, are run much faster. They are able to perform much of the same functions in much more efficient manner. 