1. The ".py" extension and they must be imported
2. ``` lotterypick = random.randrange(1,1000) ``` random methods module
3. It allows you to test blocks of code, and prevent system crashes
4. Arrays are an ordered sequence of elements able to hold different data types. 
5. Arrays use less memory and run code faster than lists. 
6. Specifies the dimension of the array, and is a data-type object. 
7. It can create multidimensional arrays and perform statisitcal analysis
through math methods. 
8.  The np.vstack, np.hstack, or the np.hsplit are all methods used with arrays. 
9.  The array shape depends on the dimensions .ndim(), number of elements .shape(), and size .size(). 
10. An array with 3+ dimensions


11. Arrays are able to use less memory, run faster, and much more efficient.
12. An empty array generates its contents from np.zeros, np.ones, or np.random.rand. Each 
one of these tells python or numpy where to grab it components from. 
13. “Python Data Analysis Library"
14. Count and namedtuple
15. Data Clease, normalization, visualization, inspection
16. To permanently sort a datefrom one must add the parameter inplace = true
17. CSV comma seperated values
18. We do not like null values 





In [28]:
import numpy as np
a = np.array([[25, 16]])
b = np.array([[11, 2], [13, 4]])
c = np.array([[7, 81], [5, 6], [11, 12]])

abc = np.concatenate((a,b,c))
print(abc)
abc_sorted = np.sort(abc)
abc_reshaped = np.array(abc_sorted, ndmin = 2)

zurk, xex, zombie, phil, dan, zerk = abc
print(zurk)
print(xex)
print(zombie)
print(phil)
print(dan)
print(zerk)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[25 16]
[11  2]
[13  4]
[ 7 81]
[5 6]
[11 12]
12


In [48]:

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboarray = np.concatenate((one, two, three))
comboarray_sorted = np.sort(comboarray)
print(comboarray)
print(comboarray[2])
print(comboarray[3:])
print(comboarray[3:15])
print(comboarray[-6:])
print(comboarray[:-9])
print(comboarray[8:23:2])
print(comboarray[-24:-1:5])



[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
12
[13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24 25 26]
[2 3 4 5 6 7]
[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26]
[20 22 24 26  0  2  4  6]
[10 15 22 27  4]


In [2]:
import numpy as np
array_f = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array_d = np.array([[17.0, 70.0, 10.7]])
print(np.add(array_d, array_f))
print(np.divide(array_f, array_d))
print(np.multiply(array_f, array_d))


[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]


In [58]:
print(np.subtract(array_d, array_f))

[[[ 17.    70.    10.6 ]
  [  7.    59.7    0.69]]

 [[ -3.    49.98  -9.4 ]
  [-13.    39.   -19.6 ]]

 [[-23.4   46.   -29.3 ]
  [  2.    54.5  -14.8 ]]]


In [60]:
divisible_by_3 = array_f[array_f % 3 == 0]
print(divisible_by_3)


[ 0.  0. 30. 24. 15.]


In [1]:
import pandas as pd


In [8]:
ingredients = pd.Series(["flour", "Milk", "Eggs", "Spam"])
quantity = pd.Series([4,1,2,1])
unit = pd.Series(["cups", "cup", "large", "can"])

cake_table = pd.concat([ingredients, quantity, unit], axis = 1)
print(cake_table)

       0  1      2
0  flour  4   cups
1   Milk  1    cup
2   Eggs  2  large
3   Spam  1    can


In [22]:
import pandas as pd
studentdata = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    })

studentdata.sort_values(by = ['Name'], ascending = False)

snacks = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentdata['snacks'] = snacks
studentdata.sort_values(by = ['address'], ascending = False)





Name  Height Qualification  address  Age        Pets           sport  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   

         snacks  
1  Cashew Fudge  
0     ice cream  
3  Carrot Halwa  
2       waffels

In [25]:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('df.csv', sep= '\t')

In [31]:
df1 = pd.DataFrame({'broccoli': [23, 25, 27], 'lemons': [90, 91, 10], 'apples': [12,12,32]}, index = ['1','2','3'])
df1.to_csv('df1.csv', sep = '\t')

#Change to csv file
price = [12, 14, 12]
df1['price'] = price
print(df1)
df1.to_csv('df1_edited.csv', sep= '\t')

   broccoli  lemons  apples  price
1        23      90      12     12
2        25      91      12     14
3        27      10      32     12
